stages: 
  transpose:
    cmd: python flatten.py
    deps:
      - flatten.py
      - raw
    outs:
      - flattened

  resize:
    cmd: python resize.py
    deps:
      - resize.py
      - flattened
    outs:
      - resized

  check_card_labels:
    cmd: python verify_cvat_pose_labels.py
    deps:
      - verify_cvat_pose_labels.py
      - resized
      - card_pose_labels
    outs:
      - card_pose_labels_verified

  check_segmentation_labels:
    cmd: python verify_sam_mask_labels.py
    deps:
      - verify_sam_mask_labels.py
      - resized
      - penis_segmentation_masks
    outs:
      - penis_segmentation_masks_verified

  join_labels:
    cmd: python join_labels.py
    deps:
      - join_labels.py
      - resized
      - card_pose_labels_verified
      - penis_segmentation_masks_verified
    outs:
      - labeled

  build_datasets:
    cmd: python build_datasets.py
    deps:
      - build_datasets.py
      - labeled
      - metadata.csv
    outs:
      - card_pose_dataset
      - penis_segmentation_dataset
      - cleaned