stages: 
  transpose:
    cmd: python flatten.py
    deps:
      - flatten.py
      - raw
    outs:
      - flattened

  resize:
    cmd: python resize.py
    deps:
      - resize.py
      - flattened
    outs:
      - resized

  check_card_labels:
    cmd: python verify_cvat_pose_labels.py
    deps:
      - verify_cvat_pose_labels.py
      - resized
    outs:
      - card_pose_labels

  check_segmentation_labels:
    cmd: python verify_sam_mask_labels.py
    deps:
      - verify_sam_mask_labels.py
      - resized
    outs:
      - penis_segmentation_masks